"""Convert datetime columns to timezone aware

Revision ID: 47fcb5356050
Revises: b8661515b7fd
Create Date: 2025-07-01 15:46:38.900801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fcb5356050'
down_revision = 'b8661515b7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objekt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objekt', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
