"""add bemerkungen and edit features

Revision ID: b8661515b7fd
Revises: 
Create Date: 2025-06-18 10:38:12.580127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8661515b7fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ausleiher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bemerkung', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ausleiher', schema=None) as batch_op:
        batch_op.drop_column('bemerkung')

    # ### end Alembic commands ###
